### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by adriankeenan** [cristijora/vue-tabs#10]
Hi,

What's the license for this project? It doesn't appear to be mentioned in the readme, docs, package.json etc.

Thanks.

**Comment by cristijora** [comment]
Sorry for that, for me everything I have as public repos = MIT licence
Added the Licence file
https://github.com/cristijora/vue-tabs/blob/master/LICENCE.md

**Comment by adriankeenan** [comment]
That's great - many thanks!
