### ISSUE TITLE
Private path in dist file

### ISSUE THREAD

**Issue by MekDrop** [cristijora/vue-tabs#11]
In `dist/vue-tabs.js` there is one line with private path:

`i.options.__file="C:\\work\\Github\\vue-tabs\\src\\components\\TabContent.vue"`

I think it's confusing when you install npm package in different path and than you get Vue message with such path.

**Comment by cristijora** [comment]
Thanks for pointing out. This is indeed not good. Is this warning shown during npm install ?

**Comment by MekDrop** [comment]
From browser console: ![screen shot 2017-07-03 at 11 36 27](https://user-images.githubusercontent.com/342641/27784760-f3a02f7e-5fe3-11e7-9827-f9ad2a2e2277.png)

**Comment by cristijora** [comment]
Can you describe the situation from which this error resulted?

**Comment by MekDrop** [comment]
I think this always happens when you are getting such warning like in my screenshot on tab child component. And that warning happens I think always when programatically props before mounted event are modified.

**Comment by cristijora** [comment]
This was fixed along with the new release which contains a totally different way of bundling the component
