### ISSUE TITLE
data can not loaded in mouted mothed.

### ISSUE THREAD

**Issue by nonefirst** [cristijora/vue-tabs#12]
https://jsfiddle.net/Lacuqsjn/
I initialize the data in mouted mothed,but warn:
Prop startIndex set to 0 is greater than the number of tabs - 0. Make sure that the starting index is less than the number of tabs registered.

and the tab was not show.
How can i solve it？

**Comment by cristijora** [comment]
@nonefirst Unfortunately tabs don't work with dynamic instantiated data for now. I know about this issue and will fix it as soon as possible (maybe today)

**Comment by nonefirst** [comment]
ok,if you have fixed it，please reply this issue

**Comment by cristijora** [comment]
Sure, I will reference the commits to the issue and update the npm version

**Comment by cristijora** [comment]
Please check the same jsfiddle from above. If it works ok, I will publish this version to npm

**Comment by nonefirst** [comment]
it's ok， tks.
