### ISSUE TITLE
Spaces affect the layout.

### ISSUE THREAD

**Issue by seekcx** [cristijora/vue-tabs#15]
In the absence of an icon, the layout looks weird and the text can not be centered.

https://github.com/cristijora/vue-tabs/blob/master/src/components/VueTabs.js#L116

**Comment by cristijora** [comment]
Can you show in a fiddle please?
Here is a starting point.
https://jsfiddle.net/b44cc4dq/309/

Maybe the space should be removed between icon and title

**Comment by seekcx** [comment]
@cristijora You are right, that's what I mean. The middle of the `&nbsp;` causes the text to look no center.

**Comment by cristijora** [comment]
@seekcx Moved the space to icon which will be added only when you define an icon for the tab.
Released https://github.com/cristijora/vue-tabs/releases/tag/v0.5.2

**Comment by seekcx** [comment]
@cristijora  Great! Thanks.

**Comment by scaytrase** [comment]
Seems like this one breaks spinning font-awesome icons now. With `&nbsp` in it they spin with wobbling. Can this one be made optional?
