### ISSUE TITLE
change theme

### ISSUE THREAD

**Issue by cyobiorah** [cristijora/vue-tabs#16]
how can the theme be changed from the default one cannot seem to find how

**Comment by cristijora** [comment]
If you use webpack simply import the css of the theme you want
https://cristijora.github.io/vue-tabs/#/?id=component-registration

```
import 'vue-nav-tabs/themes/paper.css'
```
Or 

```
import 'vue-nav-tabs/themes/material.css'
```

If you don't use webpack or npm simply import the theme as a style tag
```
<link rel="stylesheet" href="https://unpkg.com/vue-nav-tabs/themes/paper.css">
```

**Comment by cyobiorah** [comment]
thanks,  pretty easy.

**Comment by cristijora** [comment]
You could also copy the css from there and change it as you wish and reference your "own" theme if you want.

**Comment by Kondenko** [comment]
I use scss in my project and importing the scss theme version does not work. Because of that I can't import my own scss theme in my styles. It won't even work if I copy the whole theme file into my <script> tag.
What could be wrong? 

```scss
@import '~vue-nav-tabs/themes/paper.css'; // Working
@import '~vue-nav-tabs/themes/paper.scss'; // Not working
@import '~vue-nav-tabs/themes/paper'; // Not working
```
