### ISSUE TITLE
This doesn't support disabling tabs?

### ISSUE THREAD

**Issue by akashdeep-singh** [cristijora/vue-tabs#18]

**Comment by cristijora** [comment]
@akashdeep-singh Currently no, but that can be easily added 😄

**Comment by akashdeep-singh** [comment]
@cristijora I'll try adding the functionality and PR if I get soemwhere

**Comment by cristijora** [comment]
Don't worry. I almost finished it.

**Comment by cristijora** [comment]
See this fiddle as an example
https://jsfiddle.net/b44cc4dq/386/

There is a `disabled` prop per tab
and 2 options to configure the colors for disabled tabs
```html
 disabled-color="lightgrey"
 disabled-text-color="grey"
```

You can also do that via css if you want but you have to cover the hover case also.
If this is fine, I will publish to npm a new version

**Comment by akashdeep-singh** [comment]
@cristijora Thanks! Could you publish to npm as well?

**Comment by cristijora** [comment]
It's up on npm [0.5.4](https://github.com/cristijora/vue-tabs/releases/tag/v0.5.4)

**Comment by akashdeep-singh** [comment]
It doesn't seem to be working on the jsfiddle you shared. Could you verify?

**Comment by cristijora** [comment]
Maybe hard refresh? Do  you get something like this?
![image](https://user-images.githubusercontent.com/15955045/30032389-4cc0e01c-919e-11e7-8e0e-0c3c4d88cc9a.png)

**Comment by akashdeep-singh** [comment]
Yep, that worked. Thanks
