### ISSUE TITLE
Tabs not work

### ISSUE THREAD

**Issue by olive64** [cristijora/vue-tabs#2]
![capture](https://cloud.githubusercontent.com/assets/255646/25868517/3d784c1a-34fd-11e7-87dd-e56a694ea661.png)
Hi :)

the tab panel is display, but all v-tab includes are show, no error on debugger

**Comment by cristijora** [comment]
Can you show the code and the output? Is the package version 0.2.2 ?

**Comment by cristijora** [comment]
Showing the package.json version for `vue-nav-tabs` and the code where you declare the tabs would be helpful

**Comment by olive64** [comment]
Your right, my version was 0.1.2, work fine with 0.2.2
