### ISSUE TITLE
All links color turns to grey inside the tabs?

### ISSUE THREAD

**Issue by ryanelian** [cristijora/vue-tabs#20]
Note the Login URL text and the Edit button inside the tab content:

![with](https://user-images.githubusercontent.com/8892187/31475238-e4643c9a-af29-11e7-8ee8-f8718382136c.PNG)

https://github.com/cristijora/vue-tabs/blob/master/themes/vue-tabs.css#L4-L6

```css
.vue-tabs a {
  text-decoration: none;
color: gray; }
```

I feel that those lines should not be there...

It looks better too without it tbh:

![without](https://user-images.githubusercontent.com/8892187/31475242-ed26575a-af29-11e7-8838-0a84d2e5f9a4.PNG)

(Sorry for the red box censored texts btw, but I hope you get the point.)

**Comment by moondef** [comment]
Fixed
[PR](https://github.com/cristijora/vue-tabs/pull/26)
