### ISSUE TITLE
How to extend the library?

### ISSUE THREAD

**Issue by iMomen** [cristijora/vue-tabs#24]
I want to use an image in the tab instead of the icon, I have already done this by updating the main library files by replacing the icon function

`        renderIcon: function renderIcon(index) {
            var h = this.$createElement;

            if (this.tabs.length === 0) return;
            var tab = this.tabs[index];
            var icon = tab.icon;
            var imageSrc = tab.image;

            var simpleIcon = h(
                'object',
                {attrs: { data: imageSrc }}
            );
            if (!tab.$slots.title && imageSrc) return simpleIcon;
        },`

Is there is any way to use a better way? like extending the library?
I can't do this using Vuejs. 
Any advice?

**Comment by cristijora** [comment]
Hi @iMomen 
There is no need to extend it or modify it internally for this use case
You can simply use the `title` slot
https://jsfiddle.net/b44cc4dq/519/

**Comment by iMomen** [comment]
@cristijora Thank you.
But actually, 
I don't want to lose the title also, my designed tabs is something like this
<img width="993" alt="screen shot 2017-10-30 at 12 09 13" src="https://user-images.githubusercontent.com/5030329/32162787-034f3dec-bd0f-11e7-8562-688c9ccdcbb8.png">

**Comment by cristijora** [comment]
@iMomen slots are just placeholders for html. You can put anything you need inside them.
https://vuejs.org/v2/guide/components.html#Content-Distribution-with-Slots

Regarding the design part, you can write css to achieve the look from design.
Here is a starting point: https://jsfiddle.net/b44cc4dq/556/
It was done quickly so don't take it as a solid reference. Made it so you can get an idea on how to continue.

**Comment by iMomen** [comment]
Working like a charm, and thank you for telling me about Slots

Closed.
