### ISSUE TITLE
Issue when importing the style

### ISSUE THREAD

**Issue by kidii** [cristijora/vue-tabs#25]
ERROR in ./~/vue-nav-tabs/themes/vue-tabs.css
Module parse failed: /Applications/MAMP/htdocs/master/node_modules/vue-nav-tabs/themes/vue-tabs.css Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
| .vue-tabs.stacked {
|   display: flex; }
| 
 @ ./~/buble-loader!./~/vue-loader/lib/selector.js?type=script&index=0!./resources/assets/js/components/ServiceModule/_EditWorksheet.vue 10:0-41
 @ ./resources/assets/js/components/ServiceModule/_EditWorksheet.vue
 @ ./resources/assets/js/app.js

**Comment by cristijora** [comment]
Hi @kidii 
Can you tell me please what is your webpack setup ?

**Comment by kidii** [comment]
Hi!

var elixir = require('laravel-elixir');

require('laravel-elixir-vue-2');

elixir(mix => {
	mix.sass('app.scss')
	   .styles('custom.css', 'public/css/all.css')
	   .copy( 'node_modules/bootstrap-sass/assets/fonts/bootstrap', 'public/fonts/bootstrap')
	   .webpack('app.js')
	   .scripts([
			'bootstrap-notify.min.js'
	   ]);
});

**Comment by cristijora** [comment]
hm do you know if you have a `css-loader` setup ? 
Do you have other places where you import css ? (bootstrap css for example?)

**Comment by cristijora** [comment]
Try with 
```js
mix.copy('node_modules/vue-nav-tabs/themes/vue-tabs.css', 'public/css/vue-tabs.css');
```
```js
<link rel="stylesheet" href="{{ elixir('css/vue-tabs.css') }}">
```
I might be wrong since I'm not a laravel user. If this doesn't work you need to find out how to import css or add a css-loader in laravel

**Comment by kidii** [comment]
Nope. But thanks for helping! :)

**Comment by cristijora** [comment]
https://stackoverflow.com/questions/31547729/laravel-5-elixir-how-to-reference-a-css-file-from-node-modules-directory
I see people use the copy option.

**Comment by cristijora** [comment]
Closing as it's not related to vue-tabs
