### ISSUE TITLE
Hide/show tab

### ISSUE THREAD

**Issue by ameoba32** [cristijora/vue-tabs#28]
I am trying to show hidden tab, but got not that expected. At first it shows both tabs, but later fixes it when clicked. See example here https://jsfiddle.net/p63evL20/

How to achieve this? I need to temporarily hide first tab and show it later.

Thanks.

**Comment by cristijora** [comment]
Hi @ameoba32 
You could try to use `v-model` for more predictive rendering.
https://jsfiddle.net/p63evL20/7/

If you specify via v-model the initial activeTab, then the tab order is most likely to be the correct one.

**Comment by ameoba32** [comment]
Yes, v-model works, it saves current tab correctly. Thank you!

Also, if I want to switch to newly shown tab, I came up with next code
https://jsfiddle.net/p63evL20/11/

without nextTick it does not work. But its okay :)
