### ISSUE TITLE
how to control tabs switching 

### ISSUE THREAD

**Issue by jagasan** [cristijora/vue-tabs#3]
i want to control the tab switching means every tab switching time i want to ajax call and that response 
i have to show in tabs body parts

**Comment by cristijora** [comment]
I will add an event or a v-model for the tab index soon. Currently there is no default way of watching tab changes. I'll add this tomorrow

**Comment by jagasan** [comment]
thank for replay 
i am waiting for event and please make one good document

**Comment by cristijora** [comment]
Something like this https://cristijora.github.io/vue-form-wizard/#/  ?

**Comment by jagasan** [comment]
yeah these is good document

**Comment by jagasan** [comment]
form wizard is also looking good

**Comment by cristijora** [comment]
Please check https://jsfiddle.net/b44cc4dq/56/ Let me know if more information is needed on the event. Now tabIndex and tab components are sent together with the event.

**Comment by jagasan** [comment]
thank you so much
