### ISSUE TITLE
Tab link breaks hash based navigation

### ISSUE THREAD

**Issue by ahoendgen** [cristijora/vue-tabs#30]
The fix introduced with #21 breaks hash based navigations since it sets the hash everytime to `#`.

PR #29 is a possible solution to fix this.

**Comment by kikoseijo** [comment]
Agree with ahoendgen, seems we loosing navigation everytime we click on a tab.
Maybe we missing something in vue-router configuration not on the docs.?

**Comment by ahoendgen** [comment]
@kikoseijo 
you can pass a route to a tab, then it changes the route but of course you need a route for each tab

my pr was accepted so the problem is fixed in current master

**Comment by kikoseijo** [comment]
You got to remember this package its part of a premium bundle package.
You should publish the fix on a normal release.

Its not easy to install a master branch using npm. 
Until then the update breaks the navigation after clicking on a tab.

Why don't commit to a release?
Thanks.

**Comment by kikoseijo** [comment]
Please @cristijora make a release.

**Comment by cristijora** [comment]
Released [0.5.6](https://github.com/cristijora/vue-tabs/releases/tag/v0.5.6)

**Comment by kikoseijo** [comment]
Genius!!!!
