### ISSUE TITLE
Label a with href scrolls the page up.

### ISSUE THREAD

**Issue by felocru** [cristijora/vue-tabs#31]
Hello, using `href =" # "` causes the screen to scroll up. I did not find a way to change this.
It would be nice to put the `href =" title "` with the title of the `v-tab` tag.
I await your comments, thank you.

**Comment by ahoendgen** [comment]
Have a look at #30 its the same problem

**Comment by cristijora** [comment]
@felocru @ahoendgen I will fix this this week. If you have time you could also submit a PR.
@ahoendgen I saw you submitted a pr but the build file was modified instead of the source files which are located in `src/components`

**Comment by ahoendgen** [comment]
@cristijora 
sorry, my mistake. i changed this and updated the pr

**Comment by cristijora** [comment]
Released [0.5.6](https://github.com/cristijora/vue-tabs/releases/tag/v0.5.6)
