### ISSUE TITLE
Enhancement  tab-change event

### ISSUE THREAD

**Issue by kikoseijo** [cristijora/vue-tabs#32]
Hello Cristijora,

Would not be good to have a handleTabChange in 2 versions?

What I mean its will be good to have a `beforeTabChange` and a `afterTabChange`, the uses cases could be several, I guess best argument will be to be able to set things inside the tab after things got loaded.

Great work btw.

**Comment by cristijora** [comment]
Hi @kikoseijo 
Could you provide a use case please ?

**Comment by kikoseijo** [comment]
@cristijora thanks for reply.

Yes, I want to focus on an item, any field that does not exist until tab been changed.
I can't focus on this moment because does not exist till change have been completed.

Another one:

Working with tabs and maps. must re render map after tab its visible.

Does this make sense?

**Comment by cristijora** [comment]
Yes, I understand. You could use the existing tab change event and Vue.nextTick. Having 2 events won't solve too much in this case. Simply use the tab change event and place your focus logic inside Vue.nextTick

**Comment by kikoseijo** [comment]
Super!!! 
you genius... thanks for tip.-
