### ISSUE TITLE
How to prevent tab clicks jumping to top

### ISSUE THREAD

**Issue by abdullahonden** [cristijora/vue-tabs#33]
Hello Cristi,

First of thank you for this great component, we are using your Vue Paper Dashboard Pro and making some customization. As you know Vue Tabs is in that theme, and we thought we can use this in our front page too and completed the design. But if we click on the tab, it jumps to the top. I looked at your demo and our admin pages, it doesn't jump all the time. Changing the # link to #/ [fixes the problem](https://stackoverflow.com/questions/3252730/how-to-prevent-a-click-on-a-link-from-jumping-to-top-of-page), but couldn't fix it because I'm using your library as dependency, what do you think, how can I overcome this problem?

Regards.

**Comment by cristijora** [comment]
Hi @abdullahonden Please make sure you have the latest version installed. 0.5.6. There was a bug in 0.5.5 that you are describing.

**Comment by abdullahonden** [comment]
Wow, thank you :)

**Comment by cristijora** [comment]
Closing the issue if this solved the problem. Happy coding :)
