### ISSUE TITLE
duplicate key in vue 2.5.13

### ISSUE THREAD

**Issue by nathansalwen** [cristijora/vue-tabs#34]
Hi, thanks for the components.  If I run https://jsfiddle.net/b44cc4dq/245/show/ but switch to a newer version of vue (2.5.13) I see that there is a warning.  This does not seem to stop the functionality but, I believe the newer version of vue added the warning message.

vue.js:584 [Vue warn]: Duplicate keys detected: ''. This may cause an update error.

found in

---> <VueTabs>
<Root>

Thank you

**Comment by cristijora** [comment]
Hi @nathansalwen 
Thanks for reporting. This is mainly because of the example. Internally, this component relies on "title" prop. Since the example always adds a new tab with "New Tab" title, it will eventually trigger this warning. In a real example you would want to give different names for each tab.

**Comment by AykutBurak** [comment]
Well I'm working on a real project which I have different names for each tab. But I'm still getting the same warning. [Like this one](https://jsfiddle.net/b44cc4dq/2180/).

**Comment by dmotors** [comment]
I did some test using the provided example and seems the last vue version 2.5.9 is the one that still works. I'm using 2.5.13 myself and it is definitely not working with same error message.

**Comment by robschaap242** [comment]
working in 2.6.10 and I have the same error message, with a sample that has different titles and :key for each.  I'm the 4th person to point this out, don't think it's closed IMO.

**Comment by stefanbolcs** [comment]
i have the same issue vue 2 6 11

**Comment by tfdbloom** [comment]
I get the same issue. For me the case was I used slots and skiped the title (as did the [jsfiddle example](https://jsfiddle.net/b44cc4dq/245/)). Adding the title solved it for me, still keeping the slot.

```
<v-tab v-for="(tab, i) in tabs" :key="i" :title="tab.title + i">
  <template slot="title">
    <button class="tabs__link-action" @click="removeTab()">
      <oie-use-svg svg="plus" class="svg--45"></oie-use-svg>
    </button>

    {{ tab.title }}
  </template>

  <component :is="tab.content"></component>
</v-tab>

```
