### ISSUE TITLE
Back Button to a specific Tab

### ISSUE THREAD

**Issue by jpldev** [cristijora/vue-tabs#36]
Hi, how can I program a Back Button that takes me back to a specific Active Tab?

I use  vue-router, could it be with router-link?

**Comment by cristijora** [comment]
Hi there.
For router based tabs, I really recommend writing them without a library/component.
You could simply have a router view and a styled list with tabs.
This can be very trivial to do actually especially when using some css library
```html
<ul class="nav nav-tabs">
		<li class="nav-item">
			<router-link to="/page1" class="nav-link" href="#">Page1</router-link>
		</li>
		<li class="nav-item">
			<router-link to="/page2" class="nav-link" href="#">Page2</router-link>
		</li>
		<li class="nav-item">
			<router-link to="/page3" class="nav-link" href="#">Page3</router-link>
		</li>
	</ul>
	<transition name="fade" mode="out-in">
		<router-view></router-view>
	</transition>	
```
https://codesandbox.io/s/2x56qkrp70

**Comment by jpldev** [comment]
Thanks !!
