### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by drjonnicholson** [cristijora/vue-tabs#40]
Hi,

When is version 5.7 expected to be released?

I ask as at the moment to get the improvements of tab headings with scoped slot I have to pull off of git master rather than npmjs.com.

**Comment by claudeberube** [comment]
Looks like "version": "0.5.7" was not updated  in NPM yet.

**Comment by cristijora** [comment]
Sorry for the wait guys. I've been a little to busy lately.
