### ISSUE TITLE
How to use beforeChange?

### ISSUE THREAD

**Issue by san-kumar** [cristijora/vue-tabs#41]
VueTab has a `beforeChange` method with the following comment:

```
/***
         * Function to execute before tab switch. Return value must be boolean
         * If the return result is false, tab switch is restricted
         */
        beforeChange: {
            type: Function
        },
```

Unfortunately it is not working for me. Please see this JSFiddle here:

https://jsfiddle.net/qgro0w6r/

What am I doing wrong?

**Comment by cristijora** [comment]
Hello @san-kumar Really sorry for the long response. 
`beforeChange` is an old artifact which is no longer used. Please refer to the documentation to see valid props/events http://vuejs.creative-tim.com/vue-tabs/#/?id=v-tab-props

**Comment by san-kumar** [comment]
Ok thanks :) Good to know.
