### ISSUE TITLE
Compile error with webpack 2 (laravel-mix)

### ISSUE THREAD

**Issue by bram1028** [cristijora/vue-tabs#42]
I keep getting a build error with building for prod (it worked fine for dev):

```
ERROR in ./node_modules/vue-nav-tabs/dist/vue-tabs.common.js
Module build failed: Error: Couldn't find preset "vue-app" relative to directory "D:\\REMOVED\\node_modules\\vue-nav-tabs"
    at D:\REMOVED\node_modules\babel-core\lib\transformation\file\options\option-manager.js:293:19
```

I'm using it as instructed:

```
import VueNavTabs from 'vue-nav-tabs'
Vue.use(VueNavTabs)
```

I removed this from the package.json, and then the prod build worked fine:

```
  "babel": {
    "presets": [
      [
        "vue-app",
        {
          "useBuiltIns": true
        }
      ]
    ]
  },
```

Any better suggestions?

**Comment by cristijora** [comment]
Hello @bram1028 Try to import the es5 file directly from node_modules like this
`import VueNavTabs from 'vue-nav-tabs/dist/vue-tabs.common.js` and see if that works

**Comment by bradleybensmith** [comment]
Looks like it's something in my webpack config, still narrowing it down.
