### ISSUE TITLE
tab-change google maps

### ISSUE THREAD

**Issue by bonekost** [cristijora/vue-tabs#47]
If google maps is placed in another tab than first it has to be resized for showing 
(according to this [stackoverflow.com](https://stackoverflow.com/questions/14861975/resize-google-maps-when-tabs-are-triggered))

but if you use it with `tab-change` event it doesn't work

e.g:
```
methods: {
      handleTabChange(tabIndex, newTab, oldTab){
          window.google.maps.event.trigger(document.getElementById('regularMap'), 'resize')
      }
}
```

**Comment by cristijora** [comment]
@bonekost hello 
Could you provide a small codesandbox/jsifddle with that so I can help easier. 
Until then I can only suggest maybe doing that in `$nextTick` as that event occurs before actually it's displayed in DOM.

```
handleTabChange(tabIndex, newTab, oldTab){
 		this.$nextTick(()=> {
			window.google.maps.event.trigger(document.getElementById('regularMap'), 'resize')
		})
          
      }
```

If that doesn't work please provide a fiddle example. If it works we will have to close the issue as `$nextTick` is more Vue core related

**Comment by bonekost** [comment]
@cristijora it works with `$nextTick` for me.
Thanks
