### ISSUE TITLE
Adding a badge to the tab content?

### ISSUE THREAD

**Issue by ChadTaljaardt** [cristijora/vue-tabs#48]
Hello, 

Id like to be able to add a badge to the tab content, for instance as seen in this PR: https://github.com/cristijora/vue-tabs/pull/38 you can add dynamic content to headers. Is there a way to be able to highlight that content in a badge?

Thanks!

**Comment by cristijora** [comment]
hello @ChadTaljaardt You can use the `title` slot for each tab to fully customize the tab.
Here's a demo with a badge.
https://jsfiddle.net/b44cc4dq/1390/

Regarding dynamic data, yes you can pass it over and use it inside `title` slot however you want.
