### ISSUE TITLE
loading vue-tabs via laravel mix

### ISSUE THREAD

**Issue by somuraijoe** [cristijora/vue-tabs#9]
Hi,

I'm trying to load vue tabs with laravel mix in this way:

JS:
window.VueTabs=require('vue-nav-tabs');
Vue.use(VueTabs);

HTML:
    <vue-tabs>
        <v-tab title="First tab">
            First tab content
        </v-tab>

        <v-tab title="Second tab">
            Second tab content
        </v-tab>

        <v-tab title="Third tab">
            Third tab content
        </v-tab>
    </vue-tabs>

I'm receiving the bellow error. How should I initialize it ?

vue.common.js:436 [Vue warn]: Unknown custom element: <vue-tabs> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

(found in <Root>)
warn @ vue.common.js:436
createElm @ vue.common.js:4864
createChildren @ vue.common.js:4973
createElm @ vue.common.js:4879
createChildren @ vue.common.js:4973
createElm @ vue.common.js:4879
patch @ vue.common.js:5344
Vue._update @ vue.common.js:2318
updateComponent @ vue.common.js:2441
get @ vue.common.js:2780
Watcher @ vue.common.js:2763
mountComponent @ vue.common.js:2445
Vue$3.$mount @ vue.common.js:7572
Vue$3.$mount @ vue.common.js:9671
Vue._init @ vue.common.js:4012
Vue$3 @ vue.common.js:4097
(anonymous) @ demo:153
3vue.common.js:436 [Vue warn]: Unknown custom element: <v-tab> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

(found in <Root>)

**Comment by cristijora** [comment]
I'm not very familiar with laravel-mix, but by looking at the error I can say that the initialization did not work and the component is not registered. Can you only import with `require` or with `import` also ? 
Did you try 
```
import VueTabs from 'vue-nav-tabs'
Vue.use(VueTabs)
```
?

**Comment by somuraijoe** [comment]
thx, now is loading, however is displaying all the tabs content despite what I select. 
looking into

**Comment by cristijora** [comment]
Did you also import the css file ?

**Comment by somuraijoe** [comment]
that was the issue. Thx for you support.
loading by adding: 
@import "node_modules/vue-nav-tabs/dist/vue-tabs.min"; in app,scss
